require 'dmtest/tests/infrastructure/prelude_tests'
require 'dmtest/tests/infrastructure/process_tests'
require 'dmtest/tests/infrastructure/segment_tests'
require 'dmtest/tests/infrastructure/tvm_tests'
require 'dmtest/tests/infrastructure/xml_format_tests'
require 'dmtest/tests/infrastructure/metadata_tests'
require 'dmtest/tests/infrastructure/ll_instr_tests'
