require 'dmtest/tests/snapshot/creation_tests'
require 'dmtest/tests/snapshot/basic_tests'
require 'dmtest/tests/snapshot/consistency_tests'
require 'dmtest/tests/snapshot/fs_benchmark'
require 'dmtest/tests/snapshot/throughput_tests'
